# -*- coding: utf-8 -*-
"""Soal_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbfSsnmJWBOYzT2hvwCLmkPoBfiTp-a_
"""

def diagnosis_tanaman(daun_menguning, bercak_hitam, daun_berlubang, tanaman_layu):
    if daun_menguning and tanaman_layu:
        return "Diagnosa: Serangan Virus"
    elif daun_berlubang and bercak_hitam:
        retyurn "Diagnosa: Serangan Ulat"
    elif daun_menguning and not bercak_hitam and not daun_berlubang and not tanaman_layu:
        return "Diagnosa: Defisiensi Nutrisi"
    elif tanaman_layu and bercak_hitam:
        return "Diagnosa: Penyakit Jamur"
    else:
        return "Diagnosa: Gejala tidak teridentifikasi, perlu pemeriksaan lanjut"

print("Masukkan kondisi tanaman (y/n):")
daun_menguning = input("Apakah daun menguning? (y/n): ").lower() == 'y'
bercak_hitam = input("Apakah terdapat bercak hitam? (y/n): ").lower() == 'y'
daun_berlubang = input("Apakah daun berlubang? (y/n): ").lower() == 'y'
tanaman_layu = input("Apakah tanaman layu? (y/n): ").lower() == 'y'

hasil = diagnosis_tanaman(daun_menguning, bercak_hitam, daun_berlubang, tanaman_layu)
print(hasil)